** Goal of experiments
The goal is to build GUVs and SUVs which are large in size. 

** Available solutions and their concentrations

Using the protocol previously made on 29 July 2024. 
|-------------+------------------+---------------+--------------|
| Content     | Molecular weight | Concentration |       Volume |
|             |            grams |         mg/ml |           ml |
|-------------+------------------+---------------+--------------|
| DOPS        |          809.518 |           2.5 |          1.5 |
|             |                  |            10 |          0.2 |
| DOPC        |          785.593 |            10 |          inf |
| LissRhod-PE |         1300.712 |            10 | incoming 1mg |
| DOTAP       |          697.578 |           2.5 |           14 |
| NBD-DOTAP   |           710.34 |             1 |          1.5 |
| NBD-DOTAP   |           710.34 |          0.01 |          1.5 |
|-------------+------------------+---------------+--------------|

Sources:
MW: [809.518,785.593,1300.712,697.578,710.34]
https://avantilipids.com/product/840035
https://avantilipids.com/product/850375
https://avantilipids.com/product/810150
https://avantilipids.com/product/890890
https://www.medchemexpress.com/fluorescent-dotap.html

** Protocol-Experiments: August - GUV-f
We aim to make Fluorescent GUVs with DOPS and DOPC, and Liss-Rhod-PE
500mOsm/L of Sucrose buffer is made by adding 17.12 g sucrose to 100 ml water.

Using the protocol previously made on 29 July 2024. Also, 0.4 ml of this solution is left, made on 29 July, 2024. More DOPS has been ordered. 
  
|---------+---------------+--------|
| Content | Concentration | Volume |
|---------+---------------+--------|
| DOPC    | 10 mg/ml      | 800 ul |
| DOPS    | 10 mg/ml      | 80  ul |
| Rh-PE   | 0.01 mg/ml    | 50 ul  |
|---------+---------------+--------|
Out of this solution, 100ul was deposited on a large ITO (50 mm x 50 mm) and left for drying overnight.


** Protocol-Experiments: September - SUV - BSA coating
***  September 4, 2024 - SUV

Using the protocol previously made on 20 June 2024. 
|-----------+---------------+---------|
| Content   | Concentration | Volume  |
|-----------+---------------+---------|
| DOPC      | 2.5 mg/ml     | 100 ul  |
| DOTAP     | 2.5 mg/ml     | 400  ul |
| NBD-DoTAP | 0.01 mg/ml    | 100 ul  |
|           |               |         |
|-----------+---------------+---------|

So, I end up putting 100 ul of a solution into 6 vials and let them dry. 

***  September 17, 2024, Tuesday 
It turns out that 100 ul is too little and the fluorescent concentrations here are too little as well.
So, it will be better to use the 

**** Sample 1 - SUV-F
55% DOTAP Fluorescent
|-----------+---------------+----------|
| Content   | Concentration | Volume   |
|-----------+---------------+----------|
| DOPC      | 10 mg/ml      | 200 ul   |
| DOTAP     | 2.5 mg/ml     | 1000  ul |
| NBD-DoTAP | 0.01 mg/ml    | 300 ul   |
|-----------+---------------+----------|
The entire contents are left for drying overnight in a vial.


**** Sample 2 - SUV-F
38% DOTAP Fluorescent
|-----------+---------------+---------|
| Content   | Concentration | Volume  |
|-----------+---------------+---------|
| DOPC      | 10 mg/ml      | 200 ul  |
| DOTAP     | 2.5 mg/ml     | 500  ul |
| NBD-DoTAP | 0.01 mg/ml    | 300 ul  |
|           |               |         |
|-----------+---------------+---------|
The entire contents are left for drying overnight in a vial. 

**** Before DLS measurement
1ml of water was added to the dried up 55% solution. Then 500 ul of it was added to 500 ul of water. 0.8 ml of that solution was used but 0.2 ml of that got wasted. 0.6 ml of sample 1 was prepared after 15 cycles of extrusion.

For sample 2, 0.4ml of solution was added to 0.5 ml of water. 0.3 ml was wasted and 0.6 ml of final solution was made and labelled as 55 ext 2. Extrusion was done 10 times. 

For sample 3, 0.5 ml of 38% solution was added to 0.5ml of water and extruded 5 times.

For sample 4, 0.5 ml of 38% solution was added to 0.5ml water and extruded 10 times, but 0.5 ml was lost. So, we end up with 0.5 ml of solution.

*100 ul of each sample was added to 3ml of water for testing.*

***  September 23, 2024, Monday
The results of the SUV-F characterization can be found in ~/OneDrive/Work2024/BioMembranesExperiments/Experiments_Sept/Sept23/IISC_DLS_Results.
We find that the vesicles are quite uniform in size at 200 nm, although expected was 100 nm diameter for 100 nm pore size. Moreover, varying the charge didn't really materialise as Sample 1,2 had surface charge of 55% and Sample 3,4 had surface charge of 38% but the potential is measured to be the same in both cases. 
**** TODO Identify a way to measure surface charge using the DLS technique, and quantitatively establish if 10% and 90% charge is measured to be different by preparing 90% and 10% charged vesicles. 

***  September 22, 2024, Sunday - Coating the micro-pipette with BSA
In order to coat it in Glucose BSA solution, 
we take 0.045 g of BSA and mix it with 4.5 ml of 0.1 M solution of glucose (180 mg in 10 ml).

*Successfully working pressure protocol after coating overnight with BSA.*



** Protocol-Experiments: October - Viscoelasticity/osmosis - Electroformation
***  September 30, 2024, Monday
In these set of experiments we aim to vary the visco-elasticity of the medium in which vesicles are formed by varying the concentration of methyl-cellulose. At the same time, we are varying the glucose and sucrose concentrations. 

We use the medium of 0.25% methyl cellulose (0.025 g in 10 ml of water) and use it as the buffer for building our vesicles. 
For the vesicle solution we use the DOPC+NBD-DoTAP medium where 80 ul of 2.5 mg/ml solution is used in 20 ul of 0.01 mg/ml fluorescent TAP.


|-----------+---------------+--------+----------|
| Chemical  | concentration | volume | Molarity |
|-----------+---------------+--------+----------|
| DOPC      | 10 mg/ml      | 40 ul  |   99.95% |
| NBD-DoTAP | 0.01mg/ml     | 20 ul  |    0.05% |
|           |               |        |          |

60 ul of this fluid was deposited on a ITO slide and left for drying in vacuum overnight after covering it in foil to prevent photo-bleaching. 


#+BEGIN_SRC python :results output
import numpy as np
print("Hello,world")

#%% Let's make 90% charged DOTAP-DOPC (Positive, non-fluoroscent)
Chemicals = ['DOPS','DOPC','LissRhod-PE', 'DOTAP', 'NBD-DOTAP']
Concentrations = [2.5,10,0.01,2.5,0.01]; # In chloroform
MixtureVolumes = [0,40,0,0,20]; # in microliters
Molecular_Weights = [809.518,785.593,1300.712,697.578,710.34]

# Number of Weights in mixture
Weights = np.multiply(MixtureVolumes, Concentrations)
# Percentage of moles in mixture
Percentages = np.round(100000 * np.array(Weights) / np.sum(Weights)) / 1000

Moles = np.array(Weights)/np.array(Molecular_Weights)

np.set_printoptions(suppress=True, precision=5)

print('Moles')
print(Moles)
print('Weights')
print(Weights)
# Percentage of moles in mixture
print('Weight Percentages')
print(np.round(Percentages,2))
#+END_SRC

#+RESULTS:
: Hello,world
: Moles
: [0.      0.50917 0.      0.      0.00028]
: Weights
: [  0.  400.    0.    0.    0.2]
: Weight Percentages
: [ 0.   99.95  0.    0.    0.05]



***  October  1, 2024, Tuesday
We aim to make at least two columns in the same PDMS spacer plate so that we have a slightly higher throughput of at least two samples in one electroformation. 

Next we place 0.125% MC (Methyl Cellulose) with 500mM sucrose and 500mM sucrose in water into Electroformation as follows:

3 hr: 10 Hz 6 Vpp 
1 hr: 10 Hz 9 Vpp (optional)

After electroformation, air column was moved around to encourage detachment. 

Then we prepare 0.125% MC with 500mM Glucose solution and 500mM Glucose solution in water and try to observe vesicles in both cases. 

We also need two chambers for each of the two samples: 0.5 M Sucrose in water and 0.5M Sucrose in 0.125% MC Buffer.

Observations: We observed that the vesicles are obtained in both samples with size larger than 20 micrometer in diameter.
Unilamellar fluctuating vesicles are obtained in both media and under osmotic shock, provided by either glucose/sucrose or MC, they expand. Moreover, they settle in the MC media as well due to sucrose/glucose density difference.  

***  October  2, 2024, Wednesday
Plan is to do multiple experiments in a day and extract out numbers:
1. How does the area expansion change in the presence of osmotic shock
2. How does the area expansion change in the presence of fusion
3. 
