** Goal of experiments
The goal is to build GUVs and SUVs which are large in size. 

** Available solutions and their concentrations

Using the protocol previously made on 29 July 2024. 
|---------------+------------------+---------------+---------|
| Content       | Molecular weight | Concentration |     Qty |
|               |            grams |         mg/ml | g or ml |
|---------------+------------------+---------------+---------|
| DOPS          |          809.518 |           2.5 |     1.5 |
| DOPS (Powder) |                  |         25 mg |         |
| DOPC          |          785.593 |            10 |     inf |
| LissRhod-PE   |         1300.712 |          5 mg |     inf |
| DOTAP         |          697.578 |           2.5 |      14 |
| NBD-DOTAP     |           710.34 |             1 |     1.5 |
| NBD-DOTAP     |           710.34 |          0.01 |     1.5 |
| GM3           |                  |               |         |
| AOT           |                  |               |    25 g |
|---------------+------------------+---------------+---------|
|               |                  |               |         |

Sources:
MW: [809.518,785.593,1300.712,697.578,710.34]
https://avantilipids.com/product/840035
https://avantilipids.com/product/850375
https://avantilipids.com/product/810150
https://avantilipids.com/product/890890
https://www.medchemexpress.com/fluorescent-dotap.html
AOT: https://www.sigmaaldrich.com/IN/en/product/aldrich/323586

** Protocol-Experiments: August - GUV-f
We aim to make Fluorescent GUVs with DOPS and DOPC, and Liss-Rhod-PE
500mOsm/L of Sucrose buffer is made by adding 17.12 g sucrose to 100 ml water.

Using the protocol previously made on 29 July 2024. Also, 0.4 ml of this solution is left, made on 29 July, 2024. More DOPS has been ordered. 
  
|---------+---------------+--------|
| Content | Concentration | Volume |
|---------+---------------+--------|
| DOPC    | 10 mg/ml      | 800 ul |
| DOPS    | 10 mg/ml      | 80  ul |
| Rh-PE   | 0.01 mg/ml    | 50 ul  |
|---------+---------------+--------|
Out of this solution, 100ul was deposited on a large ITO (50 mm x 50 mm) and left for drying overnight.


** Protocol-Experiments: September - SUV - BSA coating
***  September 4, 2024 - SUV

Using the protocol previously made on 20 June 2024. 
|-----------+---------------+---------|
| Content   | Concentration | Volume  |
|-----------+---------------+---------|
| DOPC      | 2.5 mg/ml     | 100 ul  |
| DOTAP     | 2.5 mg/ml     | 400  ul |
| NBD-DoTAP | 0.01 mg/ml    | 100 ul  |
|           |               |         |
|-----------+---------------+---------|

So, I end up putting 100 ul of a solution into 6 vials and let them dry. 

***  September 17, 2024, Tuesday 
It turns out that 100 ul is too little and the fluorescent concentrations here are too little as well.
So, it will be better to use the 

**** Sample 1 - SUV-F
55% DOTAP Fluorescent
|-----------+---------------+----------|
| Content   | Concentration | Volume   |
|-----------+---------------+----------|
| DOPC      | 10 mg/ml      | 200 ul   |
| DOTAP     | 2.5 mg/ml     | 1000  ul |
| NBD-DoTAP | 0.01 mg/ml    | 300 ul   |
|-----------+---------------+----------|
The entire contents are left for drying overnight in a vial.


**** Sample 2 - SUV-F
38% DOTAP Fluorescent
|-----------+---------------+---------|
| Content   | Concentration | Volume  |
|-----------+---------------+---------|
| DOPC      | 10 mg/ml      | 200 ul  |
| DOTAP     | 2.5 mg/ml     | 500  ul |
| NBD-DoTAP | 0.01 mg/ml    | 300 ul  |
|           |               |         |
|-----------+---------------+---------|
The entire contents are left for drying overnight in a vial. 

**** Before DLS measurement
1ml of water was added to the dried up 55% solution. Then 500 ul of it was added to 500 ul of water. 0.8 ml of that solution was used but 0.2 ml of that got wasted. 0.6 ml of sample 1 was prepared after 15 cycles of extrusion.

For sample 2, 0.4ml of solution was added to 0.5 ml of water. 0.3 ml was wasted and 0.6 ml of final solution was made and labelled as 55 ext 2. Extrusion was done 10 times. 

For sample 3, 0.5 ml of 38% solution was added to 0.5ml of water and extruded 5 times.

For sample 4, 0.5 ml of 38% solution was added to 0.5ml water and extruded 10 times, but 0.5 ml was lost. So, we end up with 0.5 ml of solution.

*100 ul of each sample was added to 3ml of water for testing.*

***  September 23, 2024, Monday
The results of the SUV-F characterization can be found in ~/OneDrive/Work2024/BioMembranesExperiments/Experiments_Sept/Sept23/IISC_DLS_Results.
We find that the vesicles are quite uniform in size at 200 nm, although expected was 100 nm diameter for 100 nm pore size. Moreover, varying the charge didn't really materialise as Sample 1,2 had surface charge of 55% and Sample 3,4 had surface charge of 38% but the potential is measured to be the same in both cases. 
**** TODO Identify a way to measure surface charge using the DLS technique, and quantitatively establish if 10% and 90% charge is measured to be different by preparing 90% and 10% charged vesicles. 

***  September 22, 2024, Sunday - Coating the micro-pipette with BSA
In order to coat it in Glucose BSA solution, 
we take 0.045 g of BSA and mix it with 4.5 ml of 0.1 M solution of glucose (180 mg in 10 ml).

*Successfully working pressure protocol after coating overnight with BSA.*



** Protocol-Experiments: October - Viscoelasticity/osmosis - Electroformation
***  September 30, 2024, Monday
In these set of experiments we aim to vary the visco-elasticity of the medium in which vesicles are formed by varying the concentration of methyl-cellulose. At the same time, we are varying the glucose and sucrose concentrations. 

We use the medium of 0.25% methyl cellulose (0.025 g in 10 ml of water) and use it as the buffer for building our vesicles. 
For the vesicle solution we use the DOPC+NBD-DoTAP medium where 80 ul of 2.5 mg/ml solution is used in 20 ul of 0.01 mg/ml fluorescent TAP.


|-----------+---------------+--------+----------|
| Chemical  | concentration | volume | Molarity |
|-----------+---------------+--------+----------|
| DOPC      | 10 mg/ml      | 40 ul  |   99.95% |
| NBD-DoTAP | 0.01mg/ml     | 20 ul  |    0.05% |
|           |               |        |          |

60 ul of this fluid was deposited on a ITO slide and left for drying in vacuum overnight after covering it in foil to prevent photo-bleaching. 


#+BEGIN_SRC python :results output
import numpy as np
print("Hello,world")

#%% Let's make 90% charged DOTAP-DOPC (Positive, non-fluoroscent)
Chemicals = ['DOPS','DOPC','LissRhod-PE', 'DOTAP', 'NBD-DOTAP']
Concentrations = [2.5,10,0.05,2.5,0.01]; # In chloroform
MixtureVolumes = [0,85,15,0,0]; # in microliters
Molecular_Weights = [809.518,785.593,1300.712,697.578,710.34]

# Number of Weights in mixture
Weights = np.multiply(MixtureVolumes, Concentrations)
# Percentage of moles in mixture
WeightPercentages =  np.array(Weights) / np.sum(Weights) * 100

Moles = np.array(Weights)/np.array(Molecular_Weights)
MolePercentages = np.array(Moles) / np.sum(Moles) *100
np.set_printoptions(suppress=True, precision=5)

print('Moles')
print(Moles)
print('Weights')
print(Weights)
# Percentage of moles in mixture
print('weight Percentages')
print(np.round(WeightPercentages,2))
print('Mole Percentages')
print(np.round(MolePercentages,2))

#+END_SRC

#+RESULTS:
: Hello,world
: Moles
: [0.      1.08199 0.00058 0.      0.     ]
: Weights
: [  0.   850.     0.75   0.     0.  ]
: weight Percentages
: [ 0.   99.91  0.09  0.    0.  ]
: Mole Percentages
: [ 0.   99.95  0.05  0.    0.  ]



***  October  1, 2024, Tuesday
We aim to make at least two columns in the same PDMS spacer plate so that we have a slightly higher throughput of at least two samples in one electroformation. 

Next we place 0.125% MC (Methyl Cellulose) with 500mM sucrose and 500mM sucrose in water into Electroformation as follows:

3 hr: 10 Hz 6 Vpp 
1 hr: 10 Hz 9 Vpp (optional)

After electroformation, air column was moved around to encourage detachment. 

Then we prepare 0.125% MC with 500mM Glucose solution and 500mM Glucose solution in water and try to observe vesicles in both cases. 

We also need two chambers for each of the two samples: 0.5 M Sucrose in water and 0.5M Sucrose in 0.125% MC Buffer.

Observations: We observed that the vesicles are obtained in both samples with size larger than 20 micrometer in diameter.
Unilamellar fluctuating vesicles are obtained in both media and under osmotic shock, provided by either glucose/sucrose or MC, they expand. Moreover, they settle in the MC media as well due to sucrose/glucose density difference.  
**** TODO need to write the thickness of spacer

***  October  2, 2024, Wednesday 
The fluorescent solution was prepared with 80 ul of DOPC (10mg/ml) and 10 ul of NBD-DOTAP (0.01mg/ml)
Two ITO slides were coated with 40 ul of solution each. 
**** Need to make another spacer as well as frech batch of DOPC/NBD-DOTAP solutions. 
**** Start electroformation in two samples at the same time, and then use it for further experiments. 
**** Put the vesicle into water itself. If we need to control osmosis rate, we can use cholesterol.

***  October  7, 2024, Monday
 9:28 AM started electroformation for 0.25% MC with 500mM Sucrose and 0.5% MC. 
Here's what was deposited:
|-----------+---------------+--------+----------|
| Chemical  | concentration | volume | Molarity |
|-----------+---------------+--------+----------|
| DOPC      | 10 mg/ml      | 80 ul  |   99.99% |
| NBD-DoTAP | 0.01mg/ml     | 10 ul  |    0.01% |
|           |               |        |          |

45 ul of each was deposited on two plates. 
 

***  October  9, 2024, Wednesday
Plan: GM3 can sit inside the membrane itself at the time of electroformation or it can be introduced into the medium. Or both. Here we introduce via medium. 

Medium: GM3 for 5mg/ml solution. 0.5 mg in 0.5 ml. Dry 100 ul in a vial and mix it in 1 M Glucose. 

Vesicle: 0.1% fluorescent DOPC vesicle.

Following that osmotic shock will be provided.


***  October  9, 2024, Wednesday
Concentrations

**** GM3 solution protocol:
Prepare 5mg/ml solution by adding 5mg to 1ml of chloroform. 
Deposit 100 ul of this solution into a 1 ml vial and leave for drying overnight.

**** Fluorescent vesicle:
|-------------+---------------+--------+--------------|
| Chemical    | concentration | volume | Mole percent |
|-------------+---------------+--------+--------------|
| DOPC        | 10 mg/ml      | 180 ul |       99.99% |
| LissRhod-PE | 0.01mg/ml     | 20 ul  |        0.01% |
|             |               |        |              |
180 ul was used because lissRhod remaining is less and because the color is still very strong at this dilution.

***  November  7, 2024, Thursday

**** preparation of stock Liss-Rhod PE solution
We start with the stock 1mg powder of Liss-Rhod PE and then we add it to 20 ml of chloroform to get 0.05 mg/ml of solution. The beakers need to be cleaned with Chloroform. 

**** DOPC Fluorescent vesicle
This gives us 20 ml of stock solution which we can use for a long time. 

My first goal is to measure the properties of DOPC and DOPE. 

|-------------+---------------+--------+--------------|
| Chemical    | concentration | volume | Mole percent |
|-------------+---------------+--------+--------------|
| DOPC        | 2.5 mg/ml     | 90 ul  |       99.87% |
| LissRhod-PE | 0.05mg/ml     | 10 ul  |        0.13% |
|             |               |        |              |


This gives us around 0.1 % solution of Liss-Rhod PE in DOPC. 
We deposit around 45 ul of this solution on-to two ITO plates. 

This will be followed by electroformation. The inside buffer used is Sucrose and outside is Glucose. 
Electroformation will be done for 3 hours at 6 Vpp 50 Hz (It should be 6Vpp 10 Hz ideally). 


**  November  8, 2024, Friday
We performed the experiment to compare the pressure applied by the motion of vertical stage with the pressure applied by the syringe pump and also to calibrate the two. 

We observed that the pressure applied 

|-------|
|       |
| 2.527 |
| 2.417 |

0.11 +- 0.02 V corresponds to 2cm of water column height or 196 Pascals or 1.96 mBar. 
Correspondingly, for a change in volume of 10 microliters, the pressure change is 0.04 +- 0.01 V or around 70 +- 10 Pascals.
volume in the griener tube (15ml) is around 5 ml and 10+ml is empty. 
**  November 11, 2024, Monday
*** MicroPipette experiments
We make Sucrose and Glucose 1 Molar solutions by adding 3.42 grams and 1.81 grams of each into 10ml water respectively. 

We also made 0.1 M BSA solution by adding 180 mg of BSA to 10 ml of water. 

For the electroformation, I use 0.125M Sucrose solution ( 1.25 ml of 1M solution with 8.75 ml of water)

We now test the parameters for the fluorescence. We also test the density to get an estimate of dilution required. 

Need to fix the camera and the image software in such a way that it can be input into python if required in future. 

In the experiment, we first aim to slowly hold a vesicle with a slight negative pressure and once we have a hold of it, we can apply continuously increasing pressures until it bursts. 

Exposure for the 0.1 M Liss-Rhod Solution was set at 8 ms which was enough for capturing images. Not much fluorescent degradation was observed using the light continuously although we would prefer setting it up in an auto-shutter way in the future. 

*** Other Experiments: Viscoelasticity of the medium
We now have a look at how to increase visco-elasticity of a system and 

*** Other experiments: Membrane disorder control

**  November 17, 2024, Sunday
I have done: made a new chamber with a better design, and dip the pipettes in BSA and finally let the slides dry as well as GM3 dry.

**  November 18, 2024, Monday
|-------------+---------------+--------+--------------|
| Chemical    | concentration | volume | Mole percent |
|-------------+---------------+--------+--------------|
| DOPC        | 10 mg/ml      | 85 ul |       99.95% |
| LissRhod-PE | 0.05mg/ml     | 15 ul |        0.05% |
|             |               |        |              |
With this concentration, I have prepared solutions for drying, which I will dry daily. 
Moreover, I have dipped pipettes in BSA as well. 
Pulled 10 new pipettes with Program 5 in Upi's lab. Parameters for pipette puller are: ... speed 70

**  November 19, 2024, Tuesday
I have done electroformation for slide coated on both sides at 9 Vpp and 10 Hz for 3 hours from 10 am to 1 pm. 
For the lissRhod-PE, 560 nm is peak absorption and 583 nm is peak emission.

Sucrose solution was prepared at 0.5 Molarity by adding 1.715 g in 10 ml of water. 
Glucose solution at 0.5 Molarity was also prepared.
Prepared the slides of PDMS and bonded them with clean glass slide cover slip via plasma cleaning (for 2.5 minutes). 
GM3 solution which was dried up, was added as well. To the dried solution, 1 ml of water was added and this was then diluted to 10 ml and added to the solution. 




